[package]
name = "webgpu_fluid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pollster = "0.2.5"
wgpu = "0.12.0"
winit = "0.26.1"
